      # Azure CLI login
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Delete previous container if exists
      - name: Remove previous container if exists
        run: |
          az container delete \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name nitflex-production \
            --yes || true

      # Deploy new container to Azure
      - name: Deploy new container to Azure
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name nitflex-production \
            --image ${{ secrets.DOCKER_USERNAME }}/nitflex:${{ steps.project-version.outputs.version }} \
            --registry-login-server index.docker.io \
            --registry-username ${{ secrets.DOCKER_USERNAME }} \
            --registry-password ${{ secrets.DOCKER_TOKEN }} \
            --dns-name-label nitflex-production \
            --ports 8080 \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5

      # Get Azure container public FQDN
      - name: Get Azure container URL
        id: container-url
        run: |
          FQDN=$(az container show \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name nitflex-production \
            --query "ipAddress.fqdn" -o tsv)
          echo "fqdn=$FQDN" >> $GITHUB_OUTPUT

      # Load test with Artillery
      - name: Run Load Test with Artillery
        run: |
          npm install -g artillery
          artillery run load-test.yml -e staging --target http://${{ steps.container-url.outputs.fqdn }}:8080
