name: Workflow 2 - Full Test Suite Before Merge

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run Unit Tests
        run: mvn test -Dtest=*UnitTest

      - name: Run Integration Tests
        run: mvn test -Dtest=*IntegrationTest

      - name: Run System Tests (Selenium)
        run: mvn test -Dtest=*E2ETest
